@startuml
class OrderDish <<record>> {
    + Id : int <<get>> <<set>>
    + OrderId : int <<get>> <<set>>
    + DishId : int <<get>> <<set>>
    + Quantity : int <<get>> <<set>>
    + Price : decimal <<get>> <<set>>
}
@enduml
